// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO identities (user_id, provider, subject)
VALUES ($1, $2, $3)
RETURNING id, user_id, provider, subject, created_at, updated_at
`

type CreateIdentityParams struct {
	UserID   pgtype.UUID
	Provider string
	Subject  string
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, createIdentity, arg.UserID, arg.Provider, arg.Subject)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (display_name, email, email_verified, avatar_url)
VALUES ($1, $2, $3, $4)
RETURNING id, display_name, email, email_verified, avatar_url, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	DisplayName   string
	Email         string
	EmailVerified bool
	AvatarUrl     *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.DisplayName,
		arg.Email,
		arg.EmailVerified,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByIdentity = `-- name: GetUserByIdentity :one
SELECT users.id, users.display_name, users.email, users.email_verified, users.avatar_url, users.created_at, users.updated_at, users.deleted_at FROM users
JOIN identities ON identities.user_id = users.id
WHERE identities.provider = $1
  AND identities.subject = $2
  AND users.deleted_at IS NULL
`

type GetUserByIdentityParams struct {
	Provider string
	Subject  string
}

// GetUserByIdentity is the normal sign-in path: (provider, subject) is the
// identity key, never the email (spec §9).
func (q *Queries) GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentity, arg.Provider, arg.Subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVerifiedUserByEmail = `-- name: GetVerifiedUserByEmail :one
SELECT id, display_name, email, email_verified, avatar_url, created_at, updated_at, deleted_at FROM users
WHERE email = $1
  AND email_verified
  AND deleted_at IS NULL
`

// GetVerifiedUserByEmail finds a linkable account. Only verified addresses
// are considered: linking to an unverified one would let anybody claim
// somebody else's address and inherit their lists (§9).
func (q *Queries) GetVerifiedUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getVerifiedUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listIdentitySubjectsForUser = `-- name: ListIdentitySubjectsForUser :many
SELECT provider, subject FROM identities
WHERE user_id = $1
ORDER BY provider
`

type ListIdentitySubjectsForUserRow struct {
	Provider string
	Subject  string
}

// ListIdentitySubjectsForUser backs the audit line §9 asks for: every link
// event logged with both provider subjects.
func (q *Queries) ListIdentitySubjectsForUser(ctx context.Context, userID pgtype.UUID) ([]ListIdentitySubjectsForUserRow, error) {
	rows, err := q.db.Query(ctx, listIdentitySubjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIdentitySubjectsForUserRow{}
	for rows.Next() {
		var i ListIdentitySubjectsForUserRow
		if err := rows.Scan(&i.Provider, &i.Subject); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = $2,
    avatar_url = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, display_name, email, email_verified, avatar_url, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID
	DisplayName string
	AvatarUrl   *string
}

// UpdateUserProfile refreshes the display name and avatar on each sign-in,
// since the provider is authoritative for both. The email is deliberately
// not touched here: changing it would move an account between the verified
// and unverified sides of the unique index.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.DisplayName, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
