// Package store holds the pgx pool, the migration runner and the
// sqlc-generated queries (spec §5.2).
//
// Hand-written files here are store.go and migrate.go. Everything else —
// db.go, models.go and *.sql.go — is generated by `make generate` from
// sqlc.yaml, the migrations and internal/store/queries. Do not hand-edit
// those: change the SQL and regenerate, or CI's drift check will fail.
package store
