// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeRefreshToken = `-- name: ConsumeRefreshToken :one
UPDATE refresh_tokens
SET used_at = now()
WHERE token_hash = $1
  AND used_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
RETURNING id, user_id, family_id, token_hash, issued_at, expires_at, used_at, revoked_at
`

// ConsumeRefreshToken marks a token spent and returns it, in one statement.
//
// The conditions are the whole reason this is a single UPDATE rather than a
// SELECT followed by an UPDATE: two requests arriving together with the same
// token both pass a SELECT, and only one can win this. A caller that gets no
// row must then ask why — missing, already spent, revoked or expired are
// very different answers, and only one of them is an attack.
func (q *Queries) ConsumeRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, consumeRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, family_id, token_hash, issued_at, expires_at, used_at, revoked_at FROM refresh_tokens
WHERE token_hash = $1
`

// GetRefreshTokenByHash reads a token whatever its state, which is how a
// failed consume is diagnosed.
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO refresh_tokens (user_id, family_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, family_id, token_hash, issued_at, expires_at, used_at, revoked_at
`

type InsertRefreshTokenParams struct {
	UserID    pgtype.UUID
	FamilyID  pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

// InsertRefreshToken records a newly issued token. The caller supplies the
// family: a fresh uuid for a new sign-in, or the existing one when rotating.
func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :execrows
UPDATE refresh_tokens
SET revoked_at = now()
WHERE family_id = $1
  AND revoked_at IS NULL
`

// RevokeRefreshTokenFamily kills every live token descended from one
// sign-in. Already-revoked rows are left alone so revoked_at keeps the time
// of the first revocation.
func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshTokensForUser = `-- name: RevokeRefreshTokensForUser :execrows
UPDATE refresh_tokens
SET revoked_at = now()
WHERE user_id = $1
  AND revoked_at IS NULL
`

// RevokeRefreshTokensForUser logs a user out everywhere.
func (q *Queries) RevokeRefreshTokensForUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokensForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
